//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.TextView;
import com.spektra.apps.R.id;
import com.spektra.apps.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class BASTListItemView_
    extends BASTListItemView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public BASTListItemView_(Context c, BASTChooserDialog d) {
        super(c, d);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        name = ((TextView) findViewById(id.name));
        bast = ((TextView) findViewById(id.bast));
        selector = ((View) findViewById(id.action_select_bast));
        type = ((TextView) findViewById(id.type));
        bastDate = ((TextView) findViewById(id.bastDate));
        {
            View view = findViewById(id.action_select_bast);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTListItemView_.this.selectBast();
                    }

                }
                );
            }
        }
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.spektra_invoice_bast, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static BASTListItemView build(Context c, BASTChooserDialog d) {
        BASTListItemView_ instance = new BASTListItemView_(c, d);
        instance.onFinishInflate();
        return instance;
    }

}
