//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import com.spektra.apps.R.layout;
import com.spektra.apps.widget.EditSignature;

public final class BASTSignatureDialog_
    extends BASTSignatureDialog
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        injectFragmentArguments_();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        signature = ((EditSignature) findViewById(com.spektra.apps.R.id.signature));
        {
            View view = findViewById(com.spektra.apps.R.id.action_continue);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTSignatureDialog_.this.submit();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.spektra.apps.R.id.doBack);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTSignatureDialog_.this.cancelBast();
                    }

                }
                );
            }
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.spektra_invoice_signature, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static BASTSignatureDialog_.FragmentBuilder_ builder() {
        return new BASTSignatureDialog_.FragmentBuilder_();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey("orderId")) {
                try {
                    orderId = args_.getLong("orderId");
                } catch (ClassCastException e) {
                    Log.e("BASTSignatureDialog_", "Could not cast argument to the expected type, the field is left to its default value", e);
                }
            }
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public BASTSignatureDialog build() {
            BASTSignatureDialog_ fragment_ = new BASTSignatureDialog_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public BASTSignatureDialog_.FragmentBuilder_ orderId(long orderId) {
            args_.putLong("orderId", orderId);
            return this;
        }

    }

}
