//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import com.spektra.apps.R.layout;

public final class BASTChooserDialog_
    extends BASTChooserDialog
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        productType = ((TextView) findViewById(com.spektra.apps.R.id.product_type));
        bastDate = ((Button) findViewById(com.spektra.apps.R.id.bast_date));
        productName = ((TextView) findViewById(com.spektra.apps.R.id.product_name));
        bastNumber = ((EditText) findViewById(com.spektra.apps.R.id.bast_number));
        bastImageview = ((ImageView) findViewById(com.spektra.apps.R.id.imageview_bast));
        {
            View view = findViewById(com.spektra.apps.R.id.imageview_bast);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTChooserDialog_.this.selectDocument();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.spektra.apps.R.id.bast_date);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTChooserDialog_.this.selectDate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.spektra.apps.R.id.action_continue);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTChooserDialog_.this.updateProduk();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.spektra.apps.R.id.doBack);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BASTChooserDialog_.this.cancelBast();
                    }

                }
                );
            }
        }
        showProduct();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.spektra_invoice_select_bast, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static BASTChooserDialog_.FragmentBuilder_ builder() {
        return new BASTChooserDialog_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public BASTChooserDialog build() {
            BASTChooserDialog_ fragment_ = new BASTChooserDialog_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
