//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.app.Activity;
import android.content.Context;
import android.widget.TextView;
import com.spektra.apps.R.id;
import com.spektra.apps.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class InvoiceItemView_
    extends InvoiceItemView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public InvoiceItemView_(Context c) {
        super(c);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        mProduct = ((TextView) findViewById(id.do_product));
        mTotal = ((TextView) findViewById(id.do_total));
        mIdOrder = ((TextView) findViewById(id.do_orderid));
        mAtasNama = ((TextView) findViewById(id.do_datapembeli));
        mInvoiceId = ((TextView) findViewById(id.invoice_id));
        mTimeStamp = ((TextView) findViewById(id.invoice_timestamp));
        setFont();
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.spektra_invoice_list_activity, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static InvoiceItemView build(Context c) {
        InvoiceItemView_ instance = new InvoiceItemView_(c);
        instance.onFinishInflate();
        return instance;
    }

}
