//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.EditText;
import android.widget.TextView;
import com.spektra.apps.R.id;
import com.spektra.apps.R.layout;
import com.spektra.apps.R.string;

public final class SpektraLoginActivity_
    extends SpektraLoginActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.spektra_login_layout);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        errorUsername = resources_.getString(string.error_username);
        errorPassword = resources_.getString(string.error_password);
        version = resources_.getString(string.app_version_dev);
        errorKoneksi = resources_.getString(string.error_koneksi);
        errorFormat = resources_.getString(string.error_format);
        name = resources_.getString(string.app_name);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
    }

    private void afterSetContentView_() {
        mPassword = ((EditText) findViewById(id.signin_password));
        mUsername = ((EditText) findViewById(id.signin_username));
        mCodeVersion = ((TextView) findViewById(id.code_version));
        mMemberFIF = ((TextView) findViewById(id.member_fif));
        {
            View view = findViewById(id.doSignin);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraLoginActivity_.this.doSignin();
                    }

                }
                );
            }
        }
        doAfterViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static SpektraLoginActivity_.IntentBuilder_ intent(Context context) {
        return new SpektraLoginActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SpektraLoginActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SpektraLoginActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
