//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.TextView;
import android.widget.ViewAnimator;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.spektra.apps.R.id;
import com.spektra.apps.R.layout;
import com.spektra.apps.R.string;

public final class SpektraMenuActivity_
    extends SpektraMenuActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.spektra_menu_layout);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        errorAccess = resources_.getString(string.error_access);
        msgLogout = resources_.getString(string.text_konfirmasi_keluar);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
    }

    private void afterSetContentView_() {
        vaDoInvoice = ((ViewAnimator) findViewById(id.vaDoInvoice));
        mPromoTextview = ((TextView) findViewById(id.promo_textview));
        storeUser = ((TextView) findViewById(id.store_user));
        vaDoKalkulator = ((ViewAnimator) findViewById(id.vaDoKalkulator));
        mInvoiceTextview = ((TextView) findViewById(id.invoice_textview));
        storeName = ((TextView) findViewById(id.store_name));
        mOrderTextview = ((TextView) findViewById(id.order_textview));
        vaDoPromo = ((ViewAnimator) findViewById(id.vaDoPromo));
        mKalkulatorTextview = ((TextView) findViewById(id.kalkulator_textview));
        vaDoOrder = ((ViewAnimator) findViewById(id.vaDoOrder));
        {
            View view = findViewById(id.doOrder);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraMenuActivity_.this.doOrder();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.doPromo);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraMenuActivity_.this.doPromo();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.doLogout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraMenuActivity_.this.doLogout();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.doInvoice);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraMenuActivity_.this.doInvoice();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.doKalkulator);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraMenuActivity_.this.doKalkulator();
                    }

                }
                );
            }
        }
        clearDataCustomer();
        setFontface();
        doOnCreateView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static SpektraMenuActivity_.IntentBuilder_ intent(Context context) {
        return new SpektraMenuActivity_.IntentBuilder_(context);
    }

    @Override
    public void onResult(final String result) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SpektraMenuActivity_.super.onResult(result);
                } catch (RuntimeException e) {
                    Log.e("SpektraMenuActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void onBackground() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SpektraMenuActivity_.super.onBackground();
                } catch (RuntimeException e) {
                    Log.e("SpektraMenuActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SpektraMenuActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SpektraMenuActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
