//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.spektra.apps.views;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.TextView;
import com.spektra.apps.R.layout;

public final class SpektraInvoiceDetailFragment_
    extends SpektraInvoiceDetailFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        injectFragmentArguments_();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        doAlamat = ((TextView) findViewById(com.spektra.apps.R.id.do_alamat));
        catatan = ((TextView) findViewById(com.spektra.apps.R.id.invoice_notes));
        mSign = ((ImageView) findViewById(com.spektra.apps.R.id.doSignature));
        nama = ((TextView) findViewById(com.spektra.apps.R.id.invoice_nama));
        doNama = ((TextView) findViewById(com.spektra.apps.R.id.do_nama));
        mIdImage = ((ImageView) findViewById(com.spektra.apps.R.id.doIdImage));
        doCatatan = ((TextView) findViewById(com.spektra.apps.R.id.do_notes));
        namaSales = ((TextView) findViewById(com.spektra.apps.R.id.invoice_nama_sales));
        doDp = ((TextView) findViewById(com.spektra.apps.R.id.do_dp));
        mSketchImage = ((ImageView) findViewById(com.spektra.apps.R.id.doSketchImage));
        mSketchName = ((TextView) findViewById(com.spektra.apps.R.id.sketch_name));
        dp = ((TextView) findViewById(com.spektra.apps.R.id.invoice_dp));
        doOrderId = ((TextView) findViewById(com.spektra.apps.R.id.do_order));
        doTanggal = ((TextView) findViewById(com.spektra.apps.R.id.do_tanggal));
        doTotal = ((TextView) findViewById(com.spektra.apps.R.id.do_total));
        doNamaSales = ((TextView) findViewById(com.spektra.apps.R.id.do_nama_sales));
        alamat = ((TextView) findViewById(com.spektra.apps.R.id.invoice_alamat));
        mIdName = ((TextView) findViewById(com.spektra.apps.R.id.id_name));
        total = ((TextView) findViewById(com.spektra.apps.R.id.invoice_total));
        bastList = ((ListView) findViewById(com.spektra.apps.R.id.bast_list));
        {
            View view = findViewById(com.spektra.apps.R.id.doSignature);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraInvoiceDetailFragment_.this.doSignature();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.spektra.apps.R.id.doSketchImage);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraInvoiceDetailFragment_.this.doSketchImage();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.spektra.apps.R.id.doIdImage);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SpektraInvoiceDetailFragment_.this.doIdImage();
                    }

                }
                );
            }
        }
        fillTransactionData();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.spektra_invoice_detail_fragment_layout, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static SpektraInvoiceDetailFragment_.FragmentBuilder_ builder() {
        return new SpektraInvoiceDetailFragment_.FragmentBuilder_();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey("order")) {
                try {
                    order = args_.getLong("order");
                } catch (ClassCastException e) {
                    Log.e("SpektraInvoiceDetailFragment_", "Could not cast argument to the expected type, the field is left to its default value", e);
                }
            }
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public SpektraInvoiceDetailFragment build() {
            SpektraInvoiceDetailFragment_ fragment_ = new SpektraInvoiceDetailFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public SpektraInvoiceDetailFragment_.FragmentBuilder_ order(long order) {
            args_.putLong("order", order);
            return this;
        }

    }

}
